before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: fLX3brNWwd1C4U+wLNpSxTVee1Dj0r/VZ78CBVhABMsnTelNO9K9kxNE0ozb/GnPHYW756GOQeEPz1ftzA3PB0PrOO20F8WIR+BHG27hANIpqebM+A7oMhAi+GyOMtvvfpo8vULYVG09TuBTG0QPTY04LoRodulEByZtcIE0ZdDTtlScouDztBBM/8QP3OfWZbh3LNlhCytsktn7lWBrPhTZ5yg9dlP9mk+NjA/gpdGQFnl82nmCFfRb089KZJTF1Aq7qS98dQ72g/tGNp4srvErmM0hqhSzk+lnbN9ZLntk+IPdpN5UGIgYuUOb+F3PuosY1hQ3WhZFlbeI0lvtMS+O9AVeQcAF2u8OhTrnbwnn7rF1t01Rguhq+rJY1eIb569ebkpwGe6Zq9opyLBalyQfGAw0ReyZld3LalbjJu6wjVEG1u9Pdthl2RyVp9LZftgvxR/KNkXV390oixUy7Qgd6Q2dohVunkZEU1lUgDeBZ5F7wjVhBYXCPc233o7c7qAsNVqiXvMDqg8/VTYrEM2rHqPMadtwnyLcjSt1OeUhERj2tZQULhdXwcJTHQEnCJtRXomAVpBivEW98Md9VU6Y6ulLl56/6exFZ5bvJgJtsBn4LdL7zXebW8tXT4vrHSP9j6sem+RLymZJulkvllQZurAvP7LmmYGgoUnAHMM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
